### ISSUE TITLE
Add information button & modal

### ISSUE THREAD

**Issue by jenniferhail** [jenniferhail/ihavecovid#2]
**Tasks:**

- [x] Add a button that contains an information icon (min. click target 45px x 45px)
- [x] Include text for accessibility: "Get information"
- [x] Position the button at the inside of top right corner
- [ ] Clicking it should open a box with text
- [ ] Only display the icon if the content exists

**Content Ideas:**

_What is this?_
Think of this site like your online Covid convenience store. We want to make your life a little bit easier while you're sick. Check back for more updates soon.

_Who made this?_
A list of the people involved. (This will later become a larger credit section or page.)

**Comment by millertchris** [comment]
@jenniferhail have you thought about what library you want to use — or — if you want to roll your own?

I'm a fan of https://micromodal.vercel.app/ because it fully accessible out of the box and is super small.

**Comment by jenniferhail** [comment]
@millertchris I've used radix ui for other projects and they have a nice [dialog component](https://www.radix-ui.com/primitives/docs/components/dialog), so I was thinking to use that. Thanks for the recommendation though; I had forgotten about micro modal. We'll see what works best with Astro.js.

**Comment by millertchris** [comment]
@jenniferhail oh! I did not realize you wanted to use Radix UI with Astro — in that case, we should definitely leverage as much as we can in that library.

**Comment by jenniferhail** [comment]
Super useful page for figuring out radiux-ui + Astro. I had to add `client:load` to my Dialog component to get it to work. 
https://docs.astro.build/en/concepts/islands/
